import webbrowser 
import pyautogui
import time
import keyboard
import sys

print("   _____                  __        ")
print("  / ___/____  ____ ______/ /____  __")
print("  \__ \/ __ \/ __ `/ ___/ //_/ / / /")
print(" ___/ / /_/ / /_/ / /  / ,< / /_/ / ")
print("/____/ .___/\__,_/_/  /_/|_|\__, /  ")
print("    /_/                    /____/   ")
print("---------------------------------------------------------------------------")
print("Sparky's Kahoot Flooder - V1.1 - Developed by Sparkyboy")
print("---------------------------------------------------------------------------")
print()
print()


code = input("Code: ")
print()
print("---------------------------------------------------------------------------")
print()
name = input("Name: ")
print()
print("---------------------------------------------------------------------------")
print()
print("! FLODO WARNING !")
print("---------------------------------------------------------------------------")
print("Instructions: Open a new tab and wait")


time.sleep(5)


pyautogui.moveTo(959, 610)
webbrowser.open_new('https://kahoot.it/') 
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(code)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(name)
pyautogui.typewrite("1")
pyautogui.press('enter')



pyautogui.moveTo(959, 610)
webbrowser.open_new('https://kahoot.it/') 
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(code)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(name)
pyautogui.typewrite("2")
pyautogui.press('enter')

pyautogui.moveTo(959, 610)
webbrowser.open_new('https://kahoot.it/') 
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(code)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(name)
pyautogui.typewrite("3")
pyautogui.press('enter')

pyautogui.moveTo(959, 610)
webbrowser.open_new('https://kahoot.it/') 
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(code)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(name)
pyautogui.typewrite("4")
pyautogui.press('enter')

pyautogui.moveTo(959, 610)
webbrowser.open_new('https://kahoot.it/') 
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(code)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(name)
pyautogui.typewrite("5")
pyautogui.press('enter')

pyautogui.moveTo(959, 610)
webbrowser.open_new('https://kahoot.it/') 
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(code)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(name)
pyautogui.typewrite("6")
pyautogui.press('enter')

pyautogui.moveTo(959, 610)
webbrowser.open_new('https://kahoot.it/') 
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(code)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.click()
pyautogui.typewrite(name)
pyautogui.typewrite("7")
pyautogui.press('enter')

print("Flood Complete")
time.sleep(95)
print("Terminating Script")
time.sleep(5)
sys.exit()
